### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by melinstagibson** [Sharpjaws/SharpSK#21] opened 2017-06-26 02:26 UTC
Could you please have a look ar this? Im not sure what else would cause this.

https://github.com/bensku/Skript/issues/689

**Comment by Sharpjaws** [comment] 2017-06-26 09:35
Hi there, does this only happen when sharpsk is on the server? Or is it also happening with no addons at all? If so can you tell me your skript version and possibly a bit of the code that you used? (if that triggers it)

**Comment by Sharpjaws** [comment] 2017-06-26 09:49
After some testing its highly unlikely that sharpsk is the cause as I encountered no problems or errors with the latest skript and sharpsk + the addons you used on it with paperspigot 1.12. It might be another addon conflicting somehow. However this error is not coming from this addon therefore i'm closing this report.

**Closed as completed** 2017-06-26 13:44 UTC
Labels: bug, conflict
